const $=s=>document.querySelector(s),list=$('#gameList'),store=$('#storeList'),status=$('#status');let config={},catalog=[],currentRoom=null;
const setStatus=t=>status.textContent=t;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function tab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===name));if(name==='library')refresh();if(name==='store')refreshStore();if(name==='online'){refreshOnline();refreshRooms();refreshRank()}}
document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>tab(x.dataset.tab));
function row(g){const r=document.createElement('div');r.className='row';const n=document.createElement('div');n.className='game-name';n.innerHTML=`<span class="game-icon">${g.type==='exe'?'🎮':'🌐'}</span>${esc(g.name)}`;const st=document.createElement('div');st.className=g.installed?'installed':'notinstalled';st.textContent=g.installed?'100% - Ready':'Free - Not Installed';const gift=document.createElement('div');gift.textContent='—';gift.className='muted';const upd=document.createElement('div');const item=catalog.find(x=>x.id===g.storeId);if(g.storeId&&item&&g.version!==item.version){upd.innerHTML=`${esc(g.version)} → ${esc(item.version)} `;const b=document.createElement('button');b.className='small';b.textContent='Update';b.onclick=async e=>{e.stopPropagation();const x=await window.gas.update(g.storeId);if(x.error)alert(x.error);else refresh()};upd.appendChild(b)}else upd.textContent='Up to date';const score=document.createElement('div');score.textContent=item?.metascore??'—';const dev=document.createElement('div');dev.textContent=g.developer||item?.developer||'Local';r.append(n,st,gift,upd,score,dev);n.onclick=()=>action(g);return r}
async function action(g){if(g.installed){const x=await window.gas.launchGame(g.id);setStatus(x.error||'Ready');if(x.error)alert(x.error)}else{setStatus('Installing…');const x=await window.gas.install(g.storeId);setStatus(x.error||'Installed');if(x.error)alert(x.error);await refresh()}}
async function refresh(){const games=await window.gas.listGames(),q=$('#search').value.trim().toLowerCase();list.innerHTML='';const f=games.filter(g=>!q||g.name.toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name,'ja',{numeric:true}));if(!f.length)list.innerHTML='<div class="empty">ライブラリは空です</div>';else f.forEach(g=>list.appendChild(row(g)));$('#librarySub').textContent=`${games.length} games`}
async function refreshStore(){store.innerHTML='<div class="empty">Storeを読み込み中…</div>';const x=await window.gas.storeList();if(x.error){store.innerHTML=`<div class="empty">Storeを読み込めません。<br>${esc(x.error)}</div>`;return}catalog=x.games||[];const a=await window.gas.account();const owned=a.owned||[];store.innerHTML='';catalog.forEach(g=>{const c=document.createElement('div');c.className='card';c.innerHTML=`<h3>${g.type==='exe'?'🎮':'🌐'} ${esc(g.name)}</h3><p>${esc(g.description||'')}<br>Developer: ${esc(g.developer)}<br>Version: ${esc(g.version)}</p><div class="price">FREE</div>`;const b=document.createElement('button');b.textContent=owned.includes(g.id)?'ライブラリに追加済み':'無料で入手';b.disabled=owned.includes(g.id);b.onclick=async()=>{const z=await window.gas.buy(g.id);if(z.error)alert(z.error);else{await refreshStore();await refresh()}};c.appendChild(b);if(owned.includes(g.id)){const i=document.createElement('button');i.className='small';i.style.marginLeft='6px';i.textContent='Install';i.onclick=async()=>{const z=await window.gas.install(g.id);if(z.error)alert(z.error);await refresh()};c.appendChild(i)}store.appendChild(c)})}
$('#search').oninput=refresh;$('#refreshStore').onclick=refreshStore;$('#publishBtn').onclick=async()=>{const x=await window.gas.publish();$('#publishStatus').textContent=x.error||'公開しました。';if(x.error)alert(x.error);else refreshStore()};
$('#saveSettings').onclick=async()=>{config=await window.gas.setConfig({account:$('#account').value.trim()||'Player',serverUrl:$('#serverUrl').value.trim()||'http://localhost:3180'});$('#footerAccount').textContent=config.account;setStatus('Settings saved')};
async function login(register=false){const u=$('#loginUser').value.trim(),p=$('#loginPass').value;if(!u||!p)return alert('アカウント名とパスワードを入力してください。');const r=await fetch(config.serverUrl+(register?'/api/register':'/api/login'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user:u,password:p})}).then(async x=>x.json().catch(()=>({error:'通信エラー'})));if(r.error)return alert(r.error);config=await window.gas.setConfig({account:u,session:r.session});$('#footerAccount').textContent=u;refreshOnline();refreshStore()}
$('#loginBtn').onclick=()=>login(false);$('#registerBtn').onclick=()=>login(true);$('#logoutBtn').onclick=async()=>{await window.gas.logout();config=await window.gas.getConfig();$('#onlineUser').textContent='未ログイン';refreshOnline()};
async function refreshOnline(){const r=await window.gas.me();$('#onlineUser').textContent=r.user?`ログイン中: ${esc(r.user.name)}`:'未ログイン';const f=await window.gas.friends();$('#friendsList').innerHTML=f.friends?.length?f.friends.map(x=>`<div>${esc(x.name)} ${x.online?'🟢':'⚪'}</div>`).join(''):'フレンドなし'}
$('#addFriendBtn').onclick=async()=>{const name=$('#friendName').value.trim();if(!name)return;const r=await fetch(config.serverUrl+'/api/friends/add',{method:'POST',headers:{'Content-Type':'application/json','X-Session':config.session},body:JSON.stringify({user:name})}).then(x=>x.json());if(r.error)alert(r.error);else refreshOnline()};
async function refreshRooms(){const r=await window.gas.rooms();const box=$('#roomsList');box.innerHTML=r.rooms?.length?r.rooms.map(x=>`<div class="room"><b>${esc(x.name)}</b> (${x.players}/${x.maxPlayers}) <button data-id="${esc(x.id)}">参加</button><small>${esc(x.id)}</small></div>`).join(''):'公開ルームなし';box.querySelectorAll('button').forEach(b=>b.onclick=()=>joinRoom(b.dataset.id))}
$('#refreshRooms').onclick=refreshRooms;$('#createRoomBtn').onclick=async()=>{const name=$('#roomName').value.trim()||'Online Room';const r=await fetch(config.serverUrl+'/api/rooms',{method:'POST',headers:{'Content-Type':'application/json','X-Session':config.session},body:JSON.stringify({name,gameId:'sample-game',maxPlayers:4})}).then(x=>x.json());if(r.error)return alert(r.error);currentRoom=r.room;$('#roomId').value=r.room.id;renderRoom(r.room);refreshRooms()};
async function joinRoom(id){const r=await fetch(config.serverUrl+'/api/rooms/'+encodeURIComponent(id)+'/join',{method:'POST',headers:{'X-Session':config.session}}).then(x=>x.json());if(r.error)return alert(r.error);currentRoom=r.room;$('#roomId').value=id;renderRoom(r.room)}
$('#joinRoomBtn').onclick=()=>joinRoom($('#roomId').value.trim());function renderRoom(r){$('#roomInfo').innerHTML=`<b>${esc(r.name)}</b><br>Host: ${esc(r.host)}<br>Players: ${r.players.map(esc).join(', ')}<hr>${(r.messages||[]).map(m=>`<div><b>${esc(m.user)}</b>: ${esc(m.text)}</div>`).join('')||'メッセージなし'}`}
$('#sendChatBtn').onclick=async()=>{if(!currentRoom)return alert('先にルームへ参加してください。');const text=$('#chatText').value.trim();if(!text)return;const r=await fetch(config.serverUrl+'/api/rooms/'+encodeURIComponent(currentRoom.id)+'/message',{method:'POST',headers:{'Content-Type':'application/json','X-Session':config.session},body:JSON.stringify({text})}).then(x=>x.json());if(r.error)return alert(r.error);$('#chatText').value='';const q=await fetch(config.serverUrl+'/api/rooms/'+encodeURIComponent(currentRoom.id)).then(x=>x.json());if(q.room)renderRoom(q.room)};
async function refreshRank(){const r=await window.gas.leaderboard();$('#rankList').innerHTML=r.entries?.length?r.entries.map((x,i)=>`<div>${i+1}. ${esc(x.user)} — <b>${x.score}</b></div>`).join(''):'まだスコアがありません。'}$('#refreshRank').onclick=refreshRank;
(async()=>{config=await window.gas.getConfig();$('#account').value=config.account;$('#serverUrl').value=config.serverUrl;$('#footerAccount').textContent=config.account;await refresh();})();
