const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT||3180),BASE=__dirname,DB=path.join(BASE,'storage','db','store.json'),GAMES=path.join(BASE,'storage','games');
fs.mkdirSync(GAMES,{recursive:true});fs.mkdirSync(path.dirname(DB),{recursive:true});
const initial={users:{},games:{'sample-game':{id:'sample-game',name:'Game All-stars Sample',type:'html',version:'1.0.0',developer:'Game All-stars',description:'開発用の無料サンプルゲームです。',price:0,metascore:null}},rooms:{},leaderboards:{}};
function db(){try{return JSON.parse(fs.readFileSync(DB,'utf8'))}catch{return structuredClone(initial)}}
function save(x){fs.writeFileSync(DB,JSON.stringify(x,null,2))}
function hash(p,s){return crypto.scryptSync(String(p),s,32).toString('hex')}
function userName(x){return String(x||'').trim().slice(0,24)}
function auth(d,req){const h=req.headers['x-session']; if(!h||!d.sessions?.[h])return null; const u=d.sessions[h]; return d.users[u]||null}
function send(res,status,obj){const b=Buffer.from(JSON.stringify(obj));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':b.length,'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type,X-Session'});res.end(b)}
async function body(req){const a=[];for await(const c of req)a.push(c);try{return JSON.parse(Buffer.concat(a).toString()||'{}')}catch{return {}}}
function gameFile(id){if(!/^[\w-]+$/.test(id))return null;for(const e of ['.exe','.html','.htm']){const f=path.join(GAMES,id+e);if(fs.existsSync(f))return f}return null}
function publicUser(u){return {name:u.name,owned:u.owned||[],friends:u.friends||[],online:!!u.online}}
const s=http.createServer(async(req,res)=>{const u=new URL(req.url,'http://localhost'),p=u.pathname,d=db();
try{
 if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type,X-Session'});return res.end()}
 if(req.method==='GET'&&p==='/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Access-Control-Allow-Origin':'*'});return res.end('<!doctype html><meta charset=\"utf-8\"><title>Game All-stars Online</title><h1>Game All-stars Online Server</h1><p>API is running.</p><p><a href=\"/api/health\">Health check</a></p>')}
 if(req.method==='GET'&&p==='/api/health')return send(res,200,{ok:true,version:'1.1.1',time:new Date().toISOString()});
 if(req.method==='POST'&&p==='/api/register'){const x=await body(req),name=userName(x.user),pw=String(x.password||'');if(name.length<2||pw.length<4)return send(res,400,{error:'アカウント名は2文字以上、パスワードは4文字以上です。'});if(d.users[name])return send(res,409,{error:'そのアカウント名は使用されています。'});const salt=crypto.randomBytes(16).toString('hex');d.users[name]={name,salt,password:hash(pw,salt),owned:[],friends:[],online:true,createdAt:new Date().toISOString()};d.sessions??={};const token=crypto.randomBytes(24).toString('hex');d.sessions[token]=name;save(d);return send(res,200,{ok:true,session:token,user:publicUser(d.users[name])})}
 if(req.method==='POST'&&p==='/api/login'){const x=await body(req),name=userName(x.user),u0=d.users[name];if(!u0||hash(String(x.password||''),u0.salt)!==u0.password)return send(res,401,{error:'アカウント名またはパスワードが違います。'});d.sessions??={};const token=crypto.randomBytes(24).toString('hex');d.sessions[token]=name;u0.online=true;save(d);return send(res,200,{ok:true,session:token,user:publicUser(u0)})}
 if(req.method==='POST'&&p==='/api/logout'){const token=req.headers['x-session'];if(d.sessions?.[token]){const name=d.sessions[token];if(d.users[name])d.users[name].online=false;delete d.sessions[token];save(d)}return send(res,200,{ok:true})}
 if(req.method==='GET'&&p==='/api/me'){const u0=auth(d,req);if(!u0)return send(res,401,{error:'ログインしてください。'});return send(res,200,{user:publicUser(u0)})}
 if(req.method==='GET'&&p==='/api/catalog')return send(res,200,{games:Object.values(d.games)});
 if(req.method==='GET'&&p==='/api/account'){const u0=auth(d,req)||d.users[userName(u.searchParams.get('user'))];if(!u0)return send(res,401,{error:'ログインしてください。'});return send(res,200,publicUser(u0))}
 if(req.method==='POST'&&(p==='/api/claim'||p==='/api/purchase')){const u0=auth(d,req),x=await body(req);if(!u0)return send(res,401,{error:'ログインしてください。'});if(!d.games[x.gameId])return send(res,404,{error:'ゲームが見つかりません。'});if(!u0.owned.includes(x.gameId))u0.owned.push(x.gameId);save(d);return send(res,200,{ok:true,owned:true})}
 if(req.method==='GET'&&p.startsWith('/api/ownership/')){const u0=auth(d,req),id=decodeURIComponent(p.split('/').pop());if(!u0)return send(res,401,{error:'ログインしてください。'});if(!u0.owned.includes(id))return send(res,403,{error:'このゲームはライブラリに追加されていません。'});return send(res,200,{owned:true})}
 if(req.method==='POST'&&p==='/api/publish'){const u0=auth(d,req),x=await body(req);if(!u0)return send(res,401,{error:'ログインしてください。'});const id='game-'+Date.now().toString(36);d.games[id]={id,name:String(x.name||id).slice(0,80),type:x.type==='exe'?'exe':'html',version:String(x.version||'1.0.0'),developer:u0.name,description:String(x.description||'Game All-starsで公開されたゲーム').slice(0,500),price:0,metascore:null};save(d);return send(res,200,{ok:true,id})}
 if(req.method==='PUT'&&p.startsWith('/api/publish/')){const u0=auth(d,req),id=decodeURIComponent(p.split('/').pop());if(!u0)return send(res,401,{error:'ログインしてください。'});if(!d.games[id]||d.games[id].developer!==u0.name)return send(res,403,{error:'公開権限がありません。'});const ext=d.games[id].type==='exe'?'.exe':'.html',f=fs.createWriteStream(path.join(GAMES,id+ext));req.pipe(f);return f.on('finish',()=>send(res,200,{ok:true}))}
 if(req.method==='GET'&&p.startsWith('/api/download/')){const u0=auth(d,req),id=decodeURIComponent(p.split('/').pop());if(!u0)return send(res,401,{error:'ログインしてください。'});if(!u0.owned.includes(id))return send(res,403,{error:'ライブラリに追加してください。'});const f=gameFile(id);if(!f)return send(res,404,{error:'配布ファイルがありません。'});res.writeHead(200,{'Content-Type':'application/octet-stream','Access-Control-Allow-Origin':'*'});return fs.createReadStream(f).pipe(res)}
 if(req.method==='GET'&&p==='/api/friends'){const u0=auth(d,req);if(!u0)return send(res,401,{error:'ログインしてください。'});return send(res,200,{friends:(u0.friends||[]).map(n=>d.users[n]).filter(Boolean).map(publicUser)})}
 if(req.method==='POST'&&p==='/api/friends/add'){const u0=auth(d,req),x=await body(req),name=userName(x.user);if(!u0)return send(res,401,{error:'ログインしてください。'});if(!d.users[name])return send(res,404,{error:'ユーザーが見つかりません。'});if(name===u0.name)return send(res,400,{error:'自分自身は追加できません。'});u0.friends??=[];if(!u0.friends.includes(name))u0.friends.push(name);save(d);return send(res,200,{ok:true})}
 if(req.method==='GET'&&p==='/api/rooms'){return send(res,200,{rooms:Object.values(d.rooms||{}).map(r=>({...r,players:r.players.length}))})}
 if(req.method==='POST'&&p==='/api/rooms'){const u0=auth(d,req),x=await body(req);if(!u0)return send(res,401,{error:'ログインしてください。'});d.rooms??={};const id='room-'+Date.now().toString(36);d.rooms[id]={id,name:String(x.name||'Online Room').slice(0,50),gameId:String(x.gameId||''),host:u0.name,players:[u0.name],createdAt:new Date().toISOString(),maxPlayers:Math.max(2,Math.min(16,Number(x.maxPlayers||4))),messages:[]};save(d);return send(res,200,{ok:true,room:d.rooms[id]})}
 if(req.method==='POST'&&p.startsWith('/api/rooms/')&&p.endsWith('/join')){const u0=auth(d,req),id=p.split('/')[3];if(!u0)return send(res,401,{error:'ログインしてください。'});const r=d.rooms?.[id];if(!r)return send(res,404,{error:'ルームがありません。'});if(!r.players.includes(u0.name)&&r.players.length>=r.maxPlayers)return send(res,409,{error:'ルームが満員です。'});if(!r.players.includes(u0.name))r.players.push(u0.name);save(d);return send(res,200,{ok:true,room:r})}
 if(req.method==='GET'&&p.startsWith('/api/rooms/')){const id=p.split('/')[3];const r=d.rooms?.[id];if(!r)return send(res,404,{error:'ルームがありません。'});return send(res,200,{room:r})}
 if(req.method==='POST'&&p.startsWith('/api/rooms/')&&p.endsWith('/message')){const u0=auth(d,req),x=await body(req),id=p.split('/')[3],r=d.rooms?.[id];if(!u0)return send(res,401,{error:'ログインしてください。'});if(!r||!r.players.includes(u0.name))return send(res,403,{error:'ルームに参加していません。'});r.messages.push({user:u0.name,text:String(x.text||'').slice(0,300),at:new Date().toISOString()});r.messages=r.messages.slice(-100);save(d);return send(res,200,{ok:true})}
 if(req.method==='POST'&&p==='/api/score'){const u0=auth(d,req),x=await body(req);if(!u0)return send(res,401,{error:'ログインしてください。'});const gameId=String(x.gameId||'');d.leaderboards??={};d.leaderboards[gameId]??=[];d.leaderboards[gameId].push({user:u0.name,score:Number(x.score||0),at:new Date().toISOString()});d.leaderboards[gameId].sort((a,b)=>b.score-a.score);d.leaderboards[gameId]=d.leaderboards[gameId].slice(0,100);save(d);return send(res,200,{ok:true})}
 if(req.method==='GET'&&p==='/api/leaderboard'){const id=u.searchParams.get('gameId')||'sample-game';return send(res,200,{gameId:id,entries:(d.leaderboards?.[id]||[]).slice(0,20)})}
 return send(res,404,{error:'Not found'});
}catch(e){console.error(e);return send(res,500,{error:e.message})}});
if(!fs.existsSync(DB))save(initial);s.listen(PORT,'0.0.0.0',()=>console.log(`Game All-stars Online Server: http://0.0.0.0:${PORT}`));
